### ISSUE TITLE
Resource permalink forever contains original resource name

### ISSUE THREAD

**Issue by duffn** [citizenparker/swsheets#124]
Whatever name you originally put in the resource name is forever in the resource permalink. 

I think it’s reasonable to potentially change the resource name after initial creation and then it looks a bit odd to still have the original name in the URL.

I’m not suggesting changing the permalink after initial creation, but perhaps something without the resource name.

**Comment by sparkertime** [comment]
I'm not totally sure what you mean by this. My best guess is the following:

> If you create a character named "asd" and get a permalink named "ypg2fqgbm-asd", and then you rename your character to "foo", then the permalink forever remains "ypg2fqgbm-asd"

If that's what you're saying, that's not quite correct. While the URL remains "ypg2fqgbm-asd" right after you save, you'll see the new permalink becomes "ypg2fqgbm-foo" when you go back to the homepage or your list of characters.

This is because the site doesn't care about anything other than the initial code - "ypg2fqgbm"  in this case. You can navigate to "ypg2fqgbm-not-my-character-name" and it will still work just fine.

If you want to fix the fact that you get sent back to the old URL once you save your changes, that's fine with me. Be warned that you'll dive into the gnarliest part of the codebase, the `Changemap` construct I had to create in 2015 back when Ecto didn't support nested changesets.

**Comment by duffn** [comment]
> If you create a character named "asd" and get a permalink named "ypg2fqgbm-asd", and then you rename your character to "foo", then the permalink forever remains "ypg2fqgbm-asd"

That was my question and I completely missed that the permalink did get updated. Thanks for the prompt response.
