### ISSUE TITLE
Deploying 12/24 @ 8A CT

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#125]
/cc @duffn 

Just FYI, I'll be deploying master at roughly 8A Central on the morning of the 24th. I don't do this very often as deploys are actually a little hairy - as alluded to in #86, the compilation process on the server is so intense that it maxes out the RAM and comes extremely close to maxing out the swapfile size on my DigitalOcean droplet.

With the pending upgrades to Elixir and Erlang, I want to make sure I have time to troubleshoot any deployment issues that crop up as they will probably mean downtime for the site. Mornings are generally quiet on the site and are the best time to take an outage - no one waking up bright and early to roleplay.

If you have any interest in co-piloting, I'd be happy to set up a screenshare. Otherwise, just letting you know when the latest changes should go live.

**Comment by duffn** [comment]
Excellent! I’ll be unavailable that morning, but would love to tag along. Can we chat about timing and screensharing privately via email/Discord/Slack? If not, I’ll certainly try to make the next deploy.

**Comment by sparkertime** [comment]
Whew, all done! This resulted in a couple of updates to https://github.com/swsheets/ansible-swsheets but was otherwise uneventful. I took a look at the site afterwards to make sure the new features work - I decided to null out all existing ranks since a lot of characters have oddities like "Sniper Shot 2 - Rank 1". All new characters and talents will get ranks, but otherwise users will have to add them.

If you could poke around to make sure you don't see anything odd, that would be much appreciated

**Comment by duffn** [comment]
Awesome! Poking around now.

On Dec 24, 2019 7:33 AM, Scott Parker <notifications@github.com> wrote:

Whew, all done! This resulted in a couple of updates to https://github.com/swsheets/ansible-swsheets but was otherwise uneventful. I took a look at the site afterwards to make sure the new features work - I decided to null out all existing ranks since a lot of characters have oddities like "Sniper Shot 2 - Rank 1". All new characters and talents will get ranks, but otherwise users will have to add them.

If you could poke around to make sure you don't see anything odd, that would be much appreciated

**Comment by duffn** [comment]
Looking good to me!
