### ISSUE TITLE
Talents and Attacks are not guaranteed to come back in the same order you added them

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#23]
Ouch! Turns out that when you add your 10th talent or attack, you may run into ordering problems (at least in some browsers).

The root cause here is that the keys that are used to submit separate talents may be sorted on insertion order (great!) or alphabetically (boo!). In the latter case, that means the alphabetic order is 0, 1, 10, 11, 2, ...

Add an index that is submitted along with each that tracks its display order. (note to self: this should work more or less like `skill_position` on base skills.)

First report: https://community.fantasyflightgames.com/index.php?/topic/178163-announcing-swsheetscom/?p=1637380

**Comment by bknowles** [comment]
It would also be nice to be able to enter them in any order, and have them automatically sorted by alpha.  For those of us who can't spell, for example.

Longer-term, I'd like to see all the talents coming out of a database so that you don't have to enter them at all, you just select which ones are appropriate.

**Comment by sparkertime** [comment]
Hmm, I'll think about sorting talents automatically. I'm not opposed to the idea, but I also don't want to surprise folks when the ordering changes.

As for having a database of talents, I probably won't do that unfortunately. My goal for this is to essentially have an online piece of paper rather that something with all the logic and features of a tool like OggDude. I'll calculate skill rolls, but that's as fancy as I'm likely to get in the foreseeable future. I don't want to be in a situation where each new splatbook requires updates to the tool.

**Comment by bknowles** [comment]
If you're comparing yourself to OggDude's program, then note that his does track talents as each new book comes out, and which ones are available to you in what order.  He explicitly leaves out the descriptions of what each talent does, but he gives you all the structure and everything so that you can't buy something if you don't have the pre-requisites.

It's perfectly valid to say that you don't want to go to that level of detail, but in that case I would be explicit and up-front with everyone as to what you will and won't do in your code.  You don't want to disappoint people who would think that your program is a complete drop-in replacement for his character generator, if that is not actually your goal.

I greatly appreciate all your hard work so far, and where it looks like you're going with this system!  Thanks!

**Comment by sparkertime** [comment]
That's a fair point. I cover those expectations explicitly in http://swsheets.com/about as well as the README for this project, but perhaps there is more to be done.

**Comment by bknowles** [comment]
I think a one-line comment at the top of the section where people are entering in their talents should be sufficient.  Just another reminder that this is supposed to be an online piece of paper with whatever information they provide, as opposed to a complete character generator.

I mean, there are some of us who never, ever, ever read the documentation, right?  Like, it's a personal challenge to keep all the documentation in the original shrink-wrap and never opened?  ;)
