### ISSUE TITLE
Add owner to the character lists

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#40]

**Comment by bknowles** [comment]
Also Force Rank, Morality, Duty, Money, and a lot of other fields that are missing.  ;)

**Comment by sparkertime** [comment]
@bknowles Just to make sure we're on the same page, I'm talking about the character lists that look like this:

![](http://i.imgur.com/pkrd28Q.png)

I don't have a ton of screen real-estate to play with there, so I have to only consider the most important fields. Are you thinking I'd fit that list inside those small boxes?

**Comment by bknowles** [comment]
Oh, sorry.  I didn't realize you were talking about having that information presented on the top-level list of characters.

You are absolutely correct that you want to minimize the information you try to present there.  You don't want to clutter things up.

I would certainly like to see Owner there.

However, because XP is just a field that gets filled in and isn't calculated or checked anywhere, I don't know that it would be that useful to have at that level.

**Comment by sparkertime** [comment]
@bknowles Fair enough regarding XP. I will think about that a bit longer.

Out of curiosity, what were you referring to?

**Comment by bknowles** [comment]
I had originally thought you were referring to having these additional pieces of information available on the character sheets themselves.  I later realized that some of them are already present, like XP.  But if you're going to track XP, it might also be nice to be able to track other things on the character sheets, like morality, duty, etc....  Of course, some of these other things might be predicated on supporting systems like AoR and F&D, so maybe I'm just being completely silly and not seeing the trees for the forest in front of me.

Nevermind....  :8ball:

**Comment by sparkertime** [comment]
After adding system information to the character list view for #28, we definitely don't have the screen real estate to show XP. Updated this issue accordingly

**Comment by sparkertime** [comment]
I've cooled to this - those are already pretty crowded boxes. A complete redesign would be needed to include this in a way which doesn't look like butt
