### ISSUE TITLE
Selectize common "Select"-ish fields

### ISSUE THREAD

**Issue by sparkertime** [citizenparker/swsheets#44]
Some fields like Species, Career, and Specialization have a number of predefined values. I still want to allow free-form input in these fields, but it would be nice to also have a list of defined values.

[Selectize.js](http://brianreavis.github.io/selectize.js/) has a number of options for supporting single- and multi-value lookups like this. I'd like to incorporate it into the following fields:
## Character
- Species
- Career
- Specializations
## Vehicle
- Type
- Hyperdrive

**Comment by bknowles** [comment]
It would be nice to have that kind of functionality in a lot of places.  I wonder if it might be possible to have different sub-lists of this type, so that once you select the career then specialization, another one pops up for talents?

Other examples for PCs might be the standard motivations, obligations, duty, morality, etc....

Other examples for ships would be weaponry, upgrades, attachments/modifications, and anything else that might take up a hard point.

**Comment by sparkertime** [comment]
@bknowles Filtering Talents based on Specializations is really interesting. I'll definitely take that into consideration. Maybe ship attachments too, I still need to learn more about those honestly.
