### ISSUE TITLE
Falleen missing from species list

### ISSUE THREAD

**Issue by themensch** [citizenparker/swsheets#75]
Hi Team,
  I'm not seeing Falleen in the list of species.  They're in Fly Casual.

**Comment by sparkertime** [comment]
I've been thinking about this lately. The problem here is that I don't keep up with the FFG splatbooks, so I am not able to make these changes myself. While you can type whatever you want into these fields, the auto-suggest still causes periodic confusion when people don't realize they can also type things in. (I think I've seen a post on the FFG forums where you also had that problem)

I see two possible solutions:

1. I remove these lists entirely to avoid confusion (see https://github.com/swsheets/swsheets/issues/77 for discussion). I'm guessing that won't be a popular decision, but it's possibly the right one.
2. Some user who is invested in this feature takes it upon themselves to keep the list up-to-date. Right now that is all stored in https://github.com/swsheets/swsheets/blob/ef5e34d7180dbdc8a3a5491646cbd774552afdcf/web/views/character_view.ex but I would be happy to pull the species and careers out into a separate file that is easier to work with and doesn't require any programming knowledge.

What do you think?

**Comment by themensch** [comment]
Thanks for writing!   

To be honest, I like option 1 - it's easy, it is future-proof, and requires zero investment in additional books.  Seems win-win all around.  There are plenty of other places people can get a complete species list and I agree you shouldn't have the burden of buying all the books to keep up.  

I do like the idea of granting permission for a few dedicated folks to work on the tool - despite the few limitations, you've created a really great tool and I often point people to it.  I'm quite the fan of the K.I.S.S. model but I know how we roleplayers all want this or that and adding them makes a clunky, difficult-to-use tool.

**Comment by sparkertime** [comment]
Oh, great! I totally agree with your reasoning for choosing the first option!

I'm definitely happy for folks to work on the tool. I happily accept [pull requests](https://yangsu.github.io/pull-request-tutorial/) and [a few folks have even done so](http://swsheets.com/thanks). I'd love more, though!

Anyway, based on our agreement I'm going to close this and #74 in favor of doing #77 soon instead.

Thanks!
